---
title: "Explorary Data Analysis"
author: "Team Model Overfit"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Exploratory Data Analysis

```{r}
library(tidyverse)
```


## Prepare the Dataset

```{r}
games_raw <- read.csv("dataset/games.csv", header=TRUE)
gps_raw <- read.csv("dataset/gps.csv", header=TRUE)
rpe_raw <- read.csv("dataset/rpe.csv", header=TRUE)
wellness_raw <- read.csv("dataset/wellness.csv", header=TRUE)
```

## Glimpse of the Dataset

```{r}
str(games_raw)
str(gps_raw)
str(rpe_raw)
str(wellness_raw)
```

## Pre-processing the Data. 

### Dataset "wellness"

```{r}
wellness_modified <- wellness_raw %>%
    select(-Nutrition, -NutritionAdjustment, -BedTime, -WakeTime)
```

```{r}
# Boxplot of Fatigue and Menstruation
wellness_modified %>% ggplot(aes(x = Menstruation)) +
    geom_boxplot(aes(y = Fatigue))
```


### Dataset "gps"

```{r}
# Get a small dataset version of gps
g1h1p1 <- gps_raw %>% filter(GameID == 1, Half == 1, PlayerID == 2)

# Remove the zero speed and calculate the average speed.
mean((g1h1p1 %>% filter(Speed != 0.0))$Speed)

# Calculate the moving distance in half 1 for player 1
moving_dist <- mean((g1h1p1 %>% filter(Speed != 0.0))$Speed) * 60 * 8 * 45/60
```

Goal: Graph the frames about how player moved in a game. 

```{r}
# Sample game: GameID == 1
game1_data <- gps_raw %>% 
    filter(GameID == 1) %>%
    select()
```

## Challenges

### Challenged #1

```{r}
gps_cleaned <- gps_raw %>%
    select(GameID, Half, PlayerID, FrameID, GameClock, Speed)

wellness_joined <- wellness_raw %>% inner_join(games_raw, by = "Date") %>%
    select(Date, Fatigue, PlayerID)

wellness_joined <- wellness_joined[!duplicated(wellness_joined),]
gps_cleaned <- gps_cleaned %>% inner_join(wellness_joined, by="")
```

### Challenge #3

```{r}
# prepare the dataset. 
chag3 <- gps_raw %>% filter(GameID == 11, PlayerID == 12) %>%
    select(AccelX, AccelY) %>%
    head(300)

library(tweenr)

gapminder_edit <- gapminder %>%
  arrange(country, year) %>%
  select(gdpPercap,lifeExp,year,country, continent, pop) %>%
  rename(x=gdpPercap,y=lifeExp,time=year,id=country) %>%
  mutate(ease="linear")

gapminder_tween <- tween_elements(gapminder_edit,
                                  "time", "id", "ease", nframes = 300) %>%
  mutate(year = round(time), country = .group) %>%
  left_join(gapminder, by=c("country","year","continent")) %>%
  rename(population = pop.x)

chag3_tween <- tween_elements(data=chag3, time="time", ease="ease", group="id",nframes = 300)
gganimate()

p2 <- ggplot(gapminder_tween,
             aes(x=x, y=y, frame = .frame)) +
  geom_point(aes(size=population, color=continent),alpha=0.8) +
  xlab("GDP per capita") +
  ylab("Life expectancy at birth") +
  scale_x_log10(labels=comma)

gganimate(p2, filename="gapminder-tween.gif", title_frame = FALSE, interval = 0.05)
```


```{r}
library(gganimate)

chag3 <- gps_raw %>% filter(GameID == 11, PlayerID == 12) %>%
    select(AccelX, AccelY) %>%
    head(300)

chag3 <- cbind(chag3, time=1:300)


ggplot(gapminder, aes(gdpPercap, lifeExp, size = pop, colour = country)) +
  geom_point(alpha = 0.7, show.legend = FALSE) +
  scale_colour_manual(values = country_colors) +
  scale_size(range = c(2, 12)) +
  scale_x_log10() +
  facet_wrap(~continent) +
  # Here comes the gganimate specific bits
  labs(title = 'Year: {frame_time}', x = 'GDP per capita', y = 'life expectancy') +
  transition_time(year) +
  ease_aes('linear')

frame <- chag3 %>% ggplot(aes(x = AccelX, y = AccelY, color = "red")) +
    geom_point() +
    transition_time(time)

animate(frame, nframes=300, fps=1)

chag3[3,] %>% ggplot(aes(x = AccelX, y = AccelY, color = "red")) +
    geom_point()
```





















































